name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
        pws
        ls
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: List Files Afer Checkout
        run: |
        pws
        ls -a
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Daniel
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"